apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dora-metrics
  namespace: appstudio-workload-monitoring
spec:
  groups:
  - name: dora-metrics
    rules:
    - record: dora:lead_time
      expr: (dora:deploytime - on (app, image_sha) group_right (commit_hash) dora:committime)
    - record: dora:lead_time_by_app
      expr: avg by (app, commit_hash, image_sha) (dora:lead_time)
    - record: dora:lead_time_global
      expr: avg(dora:lead_time_by_app)