apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- route.yaml

images:
  - name: quay.io/abarbaro/exporters
    newName: quay.io/abarbaro/exporters
    newTag: 69500cf562373bb57b4d50f4a116d2fc4f38b794