apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
  - name: quay.io/abarbaro/exporters
    newName: quay.io/abarbaro/exporters
    newTag: 2d7e2aad41c9cd573f14e740112063f269783cb3